name: Proposer une nouvelle page ou actualité
description: Suggérez une nouvelle page ou actualité pour le site TC11
title: "[Page] "
labels: ["contenu"]
body:
  - type: input
    id: titre
    attributes:
      label: "- Titre de la page"
      placeholder: "Exemple : Résultats Interclubs 2025"
    validations:
      required: true
  - type: textarea
    id: contenu
    attributes:
      label: "- Contenu"
      placeholder: "Rédigez ici le texte de la page ou de l’actualité…"
    validations:
      required: true
  - type: dropdown
    id: categorie
    attributes:
      label: "- Catégorie"
      options:
        - Compétitions
        - Club
        - Jeunes
        - Stages
        - Animations
        - Infos pratiques
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: "- Date de publication"
      description: "Laissez vide pour utiliser la date du jour, ou indiquez une date précise au format AAAA-MM-JJ (exemple : 2025-08-12)"
      placeholder: "2025-08-12"
  - type: dropdown
    id: lienTexte
    attributes:
      label: "- Label du bouton (pour accéder à la page)"
      options:
        - Voir le détail →
        - En savoir plus →
        - Je m’inscris →
        - Découvrir →
        - Renseignements →
        - Voir l’événement →
        - Voir les résultats →
        - Inscrire mon enfant →
        - Je participe →
        - Voir le calendrier →
        - Infos et inscription →
        - Voir les photos →
    validations:
      required: true



